version: '3.8'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8885:8080

volumes:
  db_data:
